### ISSUE TITLE
hardening push metaissue

### ISSUE THREAD

**Issue by kevindrosendahl** [mlab-lattice/lattice#218]
must haves:
- [ ] [definition resolution hardening](https://github.com/mlab-lattice/lattice/issues/215)
- [ ] [harden jobs](https://github.com/mlab-lattice/lattice/issues/208)
- [ ] [definition language hardening](https://github.com/mlab-lattice/lattice/issues/191)
- [ ] [latticectl overhaul](https://github.com/mlab-lattice/lattice/issues/216)
- [ ] [audit system name length requirements](https://github.com/mlab-lattice/lattice/issues/176)
- [ ] [create date for systems](https://github.com/mlab-lattice/lattice/issues/161)
- [ ] [start/complete dates for deploys](https://github.com/mlab-lattice/lattice/issues/160)
- [ ] [start/complete dates for teardowns](https://github.com/mlab-lattice/lattice/issues/91)
- [ ] [node pool tech debt](https://github.com/mlab-lattice/lattice/issues/147)
- [ ] [environment block for command builds](https://github.com/mlab-lattice/lattice/issues/72)
- [ ] [expand architecture docs](https://github.com/mlab-lattice/lattice/issues/39)
- [ ] [include version in deploys](https://github.com/mlab-lattice/lattice/issues/115)
- [ ] [upgrade bazel to >= rules_go 0.15](https://github.com/mlab-lattice/lattice/issues/217)

nice to haves:
- [ ] [move servicemesh/cloudprovider to webhooks](https://github.com/mlab-lattice/lattice/issues/196)
- [ ] [controller state machine](https://github.com/mlab-lattice/lattice/issues/214)
- [ ] [invalid character sets](https://github.com/mlab-lattice/lattice/issues/167)
- [ ] [rename systems](https://github.com/mlab-lattice/lattice/issues/84)
- [ ] [add annotation to halt controllers from acting on a resource](https://github.com/mlab-lattice/lattice/issues/110)
- [ ] [unclear error message when using a flag and wrong command](https://github.com/mlab-lattice/lattice/issues/117)

old possibly solved issues to check on:
- [ ] [show services when tearing down](https://github.com/mlab-lattice/lattice/issues/88)
- [ ] [service NodePaths are the IDs](https://github.com/mlab-lattice/lattice/issues/99)
- [ ] [service:addresses throws 500](https://github.com/mlab-lattice/lattice/issues/132)
